### ISSUE TITLE
mocks topics.json has same record repeated, wrong data , duplicate ids, 

### ISSUE THREAD

**Issue by gary-jipp** [lighthouse-labs/photolabs-starter#3]
mocks/topics.json contains identical "Wallpapers" objects.  This will confuse students as it differs from the screenshots in Compass and will generate duplicate keys react errors.   Need different data in this file, preferably some that matches what the student is told in Compass to expect.

**Comment by senhorgomes** [comment]
Issue has been resolved in original update to Mock Data. Mock Data now has 8 original images instead of 4 images repeated twice. New screenshots have been added to compass as well
